# -*- coding: utf-8 -*-
"""object_detection_utils.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ivy0q-lURzKbyEYI2JpOSgD5TTb8B_XX
"""

# import yolo for object detection
from ultralytics import YOLO

# import torchvision for image preprocessing
from torchvision import transforms

# import matplotlib and PIL to better display results
import matplotlib.pyplot as plt
from PIL import Image

# import pandas for dataframe structure
import pandas as pd

# Display results from model and resize it
def display_and_resize_results(results, scale_factor=1.0):
    """
    Displays the results from the YOLO model and resizes the output image to a given scale.

    Args:
        results: The results object from the YOLO model.
        scale_factor (float): The factor by which to scale the image.

    Returns:
        PIL.Image.Image: The resized image.
    """
    # Get the original image from the results
    img = Image.fromarray(results[0].plot())

    # Calculate new dimensions based on the scale factor
    original_width, original_height = img.size
    new_width = int(original_width * scale_factor)
    new_height = int(original_height * scale_factor)
    resized_img = img.resize((new_width, new_height))

    # Display the resized image
    plt.figure(figsize=(new_width/100, new_height/100)) # Adjust figure size for better display
    plt.axis('off')
    plt.imshow(resized_img)
    plt.show()

    return resized_img

def detect_and_display_objects(image_path, model_name='yolov8n.pt', scale_factor=1.0, display_image=True):
    """
    Performs object detection on an image using a specified YOLO model and displays the results.

    Args:
        image_path (str): The path to the input image.
        model_name (str): The name of the pretrained YOLO model to use. Defaults to 'yolov8n.pt'.
        scale_factor (float): The factor by which to scale the displayed image. Defaults to 1.0.
        display_image (bool): Whether to display the image with detections. Defaults to True.
    """
    # Load the specified pretrained YOLO model
    model = YOLO(model_name)

    # Load image
    init_img = Image.open(image_path)

    # Run object detection on the image
    results = model(init_img)

    # Display and resize the results
    if display_image:
      display_and_resize_results(results, scale_factor=scale_factor)

    # Return the results
    return results

def detect_objects_and_save_csv(image_path, output_csv_path='detected_objects.csv', model_name='yolov8n.pt'):
    """
    Performs object detection on an image using a specified YOLO model and saves the detected objects and their likelihoods to a CSV file.

    Args:
        image_path (str): The path to the input image.
        output_csv_path (str): The path to save the output CSV file. Defaults to 'detected_objects.csv'.
        model_name (str): The name of the pretrained YOLO model to use. Defaults to 'yolov8n.pt'.
    """
    # Load the specified pretrained YOLO model
    model = YOLO(model_name)

    # Load image
    init_img = Image.open(image_path)

    # Run object detection on the image
    results = model(init_img)

    # Extract detected objects and their likelihoods
    detected_objects_list = []
    for r in results:
        for box in r.boxes:
            class_id = int(box.cls)
            confidence = float(box.conf)
            class_name = model.names[class_id]
            detected_objects_list.append({'object': class_name, 'likelihood': confidence})

    # Create a pandas DataFrame from the results
    df = pd.DataFrame(detected_objects_list)

    # Save the DataFrame to a CSV file
    df.to_csv(output_csv_path, index=False)

    print(f"Detection results saved to {output_csv_path}")